/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

/**
 *
 * @author kinnder@mail.ru
 */
public class EEGDataProcessorFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = -5065287789826423012L;

	/**
	 * Creates new form EEGDataProcessorFrame
	 */
	public EEGDataProcessorFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jtaOutput = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jtParameters = new javax.swing.JTable();
		jmbMainMenu = new javax.swing.JMenuBar();
		jmFile = new javax.swing.JMenu();
		jmiSelectFiles = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JPopupMenu.Separator();
		jmiExit = new javax.swing.JMenuItem();
		jmTask = new javax.swing.JMenu();
		jmiPrepareSeparateTestFiles = new javax.swing.JMenuItem();
		jmHelp = new javax.swing.JMenu();
		jmiHelp = new javax.swing.JMenuItem();
		jmiAbout = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("EEGDataProcessor");

		jtaOutput.setEditable(false);
		jtaOutput.setColumns(20);
		jtaOutput.setRows(5);
		jScrollPane1.setViewportView(jtaOutput);

		jtParameters.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "signalTime", "300" }, { "interval_right", null }, { "interval_left", null },
						{ "duration_average", null }, { "triggerTime_average", null } },
				new String[] { "Параметр", "Значение" }) {
			private static final long serialVersionUID = -7692149791349207355L;
			Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, true };

			public Class<?> getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane2.setViewportView(jtParameters);

		jmFile.setText("Файл");

		jmiSelectFiles.setText("Выбрать файлы...");
		jmFile.add(jmiSelectFiles);
		jmFile.add(jSeparator1);

		jmiExit.setText("Выход");
		jmFile.add(jmiExit);

		jmbMainMenu.add(jmFile);

		jmTask.setText("Задача");

		jmiPrepareSeparateTestFiles.setText("Подготовить файлы \"Отдельная проба\"");
		jmTask.add(jmiPrepareSeparateTestFiles);

		jmbMainMenu.add(jmTask);

		jmHelp.setText("?");

		jmiHelp.setText("Справка");
		jmHelp.add(jmiHelp);

		jmiAbout.setText("О программе...");
		jmHelp.add(jmiAbout);

		jmbMainMenu.add(jmHelp);

		setJMenuBar(jmbMainMenu);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EEGDataProcessorFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new EEGDataProcessorFrame().setVisible(true);
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JPopupMenu.Separator jSeparator1;
	private javax.swing.JMenu jmFile;
	private javax.swing.JMenu jmHelp;
	private javax.swing.JMenu jmTask;
	private javax.swing.JMenuBar jmbMainMenu;
	private javax.swing.JMenuItem jmiAbout;
	private javax.swing.JMenuItem jmiExit;
	private javax.swing.JMenuItem jmiHelp;
	private javax.swing.JMenuItem jmiPrepareSeparateTestFiles;
	private javax.swing.JMenuItem jmiSelectFiles;
	private javax.swing.JTable jtParameters;
	private javax.swing.JTextArea jtaOutput;
	// End of variables declaration//GEN-END:variables
}
