package frame;

import application.ApplicationData;
import java.io.File;
import javax.swing.JFileChooser;

public class SelectFilesFrame extends javax.swing.JDialog {

	private static final long serialVersionUID = 2531851493293695868L;

	/**
	 * Creates new form SelectFilesView
	 */
	public SelectFilesFrame() {
		initComponents();
		setModal(true);
	}

	private ApplicationData applicationData;

	public SelectFilesFrame(ApplicationData applicationData) {
		this();
		this.applicationData = applicationData;
		jtfSamplesFile.setText(applicationData.getSamplesFileName());
		jtfIndicationsFile.setText(applicationData.getIndicationsFileName());
		jtfOutputFolder.setText(applicationData.getOutputFolder());
		jfcSelectFile.setCurrentDirectory(new File("").getAbsoluteFile());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jfcSelectFile = new javax.swing.JFileChooser();
		jtfIndicationsFile = new javax.swing.JTextField();
		jbSelectIndicationsFile = new javax.swing.JButton();
		jbSelectSamplesFile = new javax.swing.JButton();
		jtfSamplesFile = new javax.swing.JTextField();
		jlSamplesFile = new javax.swing.JLabel();
		jlIndicationsFile = new javax.swing.JLabel();
		jbDone = new javax.swing.JButton();
		jbCancel = new javax.swing.JButton();
		jlOutputFolder = new javax.swing.JLabel();
		jtfOutputFolder = new javax.swing.JTextField();
		jbSelectOutputFolder = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Выберите файлы");
		setLocationByPlatform(true);
		setResizable(false);
		setType(java.awt.Window.Type.POPUP);

		jbSelectIndicationsFile.setText("jButton2");
		jbSelectIndicationsFile.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbSelectIndicationsFileActionPerformed(evt);
			}
		});

		jbSelectSamplesFile.setText("jButton1");
		jbSelectSamplesFile.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbSelectSamplesFileActionPerformed(evt);
			}
		});

		jlSamplesFile.setText("Файл меток");

		jlIndicationsFile.setText("Файл данных");

		jbDone.setText("Готово");
		jbDone.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbDoneActionPerformed(evt);
			}
		});

		jbCancel.setText("Отмена");
		jbCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbCancelActionPerformed(evt);
			}
		});

		jlOutputFolder.setText("Папка результат");

		jbSelectOutputFolder.setText("jButton5");
		jbSelectOutputFolder.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbSelectOutputFolderActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(143, Short.MAX_VALUE).addComponent(jbDone)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jbCancel).addGap(11, 11, 11))
				.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addComponent(jtfSamplesFile)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbSelectSamplesFile, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jtfOutputFolder).addComponent(jtfIndicationsFile))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jbSelectIndicationsFile,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jbSelectOutputFolder, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jlIndicationsFile).addComponent(jlSamplesFile)
										.addComponent(jlOutputFolder))
								.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(jlSamplesFile).addGap(4, 4, 4)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jtfSamplesFile, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jbSelectSamplesFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jlIndicationsFile).addGap(2, 2, 2)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jtfIndicationsFile, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jbSelectIndicationsFile))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jlOutputFolder).addGap(1, 1, 1)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jtfOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jbSelectOutputFolder))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jbCancel).addComponent(jbDone))
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbCancelActionPerformed
		this.dispose();
	}// GEN-LAST:event_jbCancelActionPerformed

	private void jbDoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbDoneActionPerformed
		applicationData.setSamplesFileName(jtfSamplesFile.getText());
		applicationData.setIndicationsFileName(jtfIndicationsFile.getText());
		applicationData.setOutputFolder(jtfOutputFolder.getText());
		this.dispose();
	}// GEN-LAST:event_jbDoneActionPerformed

	private void jbSelectSamplesFileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbSelectSamplesFileActionPerformed
		jfcSelectFile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		int result = jfcSelectFile.showOpenDialog(this);
		if (result == JFileChooser.APPROVE_OPTION) {
			String path = jfcSelectFile.getSelectedFile().getPath();
			jtfSamplesFile.setText(path);
		}
	}// GEN-LAST:event_jbSelectSamplesFileActionPerformed

	private void jbSelectIndicationsFileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbSelectIndicationsFileActionPerformed
		jfcSelectFile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		int result = jfcSelectFile.showOpenDialog(this);
		if (result == JFileChooser.APPROVE_OPTION) {
			String path = jfcSelectFile.getSelectedFile().getPath();
			jtfIndicationsFile.setText(path);
		}
	}// GEN-LAST:event_jbSelectIndicationsFileActionPerformed

	private void jbSelectOutputFolderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbSelectOutputFolderActionPerformed
		jfcSelectFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		int result = jfcSelectFile.showOpenDialog(this);
		if (result == JFileChooser.APPROVE_OPTION) {
			String path = jfcSelectFile.getSelectedFile().getPath();
			jtfOutputFolder.setText(path);
		}
	}// GEN-LAST:event_jbSelectOutputFolderActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jbCancel;
	private javax.swing.JButton jbDone;
	private javax.swing.JButton jbSelectIndicationsFile;
	private javax.swing.JButton jbSelectOutputFolder;
	private javax.swing.JButton jbSelectSamplesFile;
	private javax.swing.JFileChooser jfcSelectFile;
	private javax.swing.JLabel jlIndicationsFile;
	private javax.swing.JLabel jlOutputFolder;
	private javax.swing.JLabel jlSamplesFile;
	private javax.swing.JTextField jtfIndicationsFile;
	private javax.swing.JTextField jtfOutputFolder;
	private javax.swing.JTextField jtfSamplesFile;
	// End of variables declaration//GEN-END:variables
}
