/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import application.ApplicationData;
import features.PrepareSeparateTestFiles;

/**
 *
 * @author kinnder@mail.ru
 */
public class TaskProgressFrame extends javax.swing.JDialog {

	private static final long serialVersionUID = 1488232629320424390L;

	/**
	 * Creates new form TaskProgressFrame
	 */
	public TaskProgressFrame() {
		initComponents();
		setModal(true);
	}

	private ApplicationData applicationData;

	public TaskProgressFrame(ApplicationData applicationData) {
		this();
		this.applicationData = applicationData;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jpbProgress = new javax.swing.JProgressBar();
		jbCancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Выполнение");
		setLocationByPlatform(true);
		setType(java.awt.Window.Type.UTILITY);
		addComponentListener(new java.awt.event.ComponentAdapter() {
			public void componentShown(java.awt.event.ComponentEvent evt) {
				formComponentShown(evt);
			}
		});

		jbCancel.setText("Отмена");
		jbCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbCancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jpbProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jbCancel)))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addComponent(jpbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jbCancel).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbCancelActionPerformed
		this.dispose();
	}// GEN-LAST:event_jbCancelActionPerformed

	private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
		// TODO add your handling code here:
		PrepareSeparateTestFiles feature = new PrepareSeparateTestFiles(applicationData);
		jpbProgress.setValue(0);
		feature.action();
		jpbProgress.setValue(100);
	}// GEN-LAST:event_formComponentShown

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the look and feel */
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TaskProgressFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new TaskProgressFrame().setVisible(true);
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jbCancel;
	private javax.swing.JProgressBar jpbProgress;
	// End of variables declaration//GEN-END:variables
}
